server.port=${PORT_NUMBER}

server.servlet.contextPath = ${CONTEXT_PATH:/cld}

cloud.aws.access-key = ${CLOUD_AWS_ACCESS_KEY:}
cloud.aws.secret-key =${CLOUD_AWS_SECRET_KEY:}
cloud.aws.region =${CLOUD_AWS_REGION:}
cloud.aws.s3.bucket =${CLOUD_AWS_S3_BUCKET:}

# Total request size limit
#spring.servlet.multipart.max-file-size=10MB
#spring.servlet.multipart.max-request-size=10MB